[package]
name = "psyche-coordinator"
version.workspace = true
edition = "2021"

[dependencies]
psyche-core.workspace = true
async-trait.workspace = true
anchor-lang.workspace = true
bytemuck.workspace = true
serde_with.workspace = true
serde.workspace = true
cfg_eval = "0.1.2"
ts-rs.workspace = true

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports", "async_tokio"] }
bincode = "1.3"
toml = { workspace = true }
rand = { workspace = true }

[[bench]]
name = "serialization_bench"
harness = false

[[bench]]
name = "consensus_bench"
harness = false
